-- MySQL Script generated by MySQL Workbench
-- 09/13/16 14:41:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PersonaDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PersonaDB` ;

-- -----------------------------------------------------
-- Schema PersonaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PersonaDB` DEFAULT CHARACTER SET utf8 ;
USE `PersonaDB` ;

-- -----------------------------------------------------
-- Table `PersonaDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonaDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `PersonaDB`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `facebook_id` BIGINT(30) NULL,
  `twitter_id` BIGINT(30) NULL,
  `google_id` BIGINT(30) NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonaDB`.`Quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonaDB`.`Quizzes` ;

CREATE TABLE IF NOT EXISTS `PersonaDB`.`Quizzes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NULL,
  `creation_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_quiz_for_owner_user_id`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `PersonaDB`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_owner_user_id_idx` ON `PersonaDB`.`Quizzes` (`owner_user_id` ASC);


-- -----------------------------------------------------
-- Table `PersonaDB`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonaDB`.`Questions` ;

CREATE TABLE IF NOT EXISTS `PersonaDB`.`Questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `content` VARCHAR(256) NULL,
  `type` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_question_for_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `PersonaDB`.`Quizzes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_quiz_id_idx` ON `PersonaDB`.`Questions` (`quiz_id` ASC);


-- -----------------------------------------------------
-- Table `PersonaDB`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonaDB`.`Answers` ;

CREATE TABLE IF NOT EXISTS `PersonaDB`.`Answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `content` VARCHAR(256) NOT NULL,
  `correct` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_answer_for_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `PersonaDB`.`Questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_question_id_idx` ON `PersonaDB`.`Answers` (`question_id` ASC);


-- -----------------------------------------------------
-- Table `PersonaDB`.`UserQuestionSolution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonaDB`.`UserQuestionSolution` ;

CREATE TABLE IF NOT EXISTS `PersonaDB`.`UserQuestionSolution` (
  `user_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `question_id`, `answer_id`, `quiz_id`),
  CONSTRAINT `fk_u_ques_s_for_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `PersonaDB`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_ques_s_for_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `PersonaDB`.`Questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_ques_s_for_answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `PersonaDB`.`Answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_ques_s_for_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `PersonaDB`.`Quizzes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_question_id_idx` ON `PersonaDB`.`UserQuestionSolution` (`question_id` ASC);

CREATE INDEX `fk_answer_id_idx` ON `PersonaDB`.`UserQuestionSolution` (`answer_id` ASC);

CREATE INDEX `fk_quiz_id_idx` ON `PersonaDB`.`UserQuestionSolution` (`quiz_id` ASC);


-- -----------------------------------------------------
-- Table `PersonaDB`.`UserQuizSolution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonaDB`.`UserQuizSolution` ;

CREATE TABLE IF NOT EXISTS `PersonaDB`.`UserQuizSolution` (
  `user_id` INT NOT NULL,
  `quiz_id` INT NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`user_id`, `quiz_id`),
  CONSTRAINT `fk_u_quiz_s_for_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `PersonaDB`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_quiz_s_for_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `PersonaDB`.`Quizzes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_quiz_id_idx` ON `PersonaDB`.`UserQuizSolution` (`quiz_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
